#!/bin/sh
# Xcode Cloud runs this right after cloning. The Xcode project is generated by
# XcodeGen (not committed), so regenerate it here before the build resolves.
set -e
echo "▸ Installing XcodeGen…"
which xcodegen >/dev/null 2>&1 || brew install xcodegen
echo "▸ Generating Garagely.xcodeproj…"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
echo "✓ ci_post_clone done"
